name: Test on Azure with Python 3.7
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Install dependencies
        run: |
          make install-azure
      - name: Lint with Pylint
        run: |
          make lint
      - name: Test with Pytest
        run: |
          make test
